### PR TITLE
Add sanity tests for all supported Ansible versions

### PR DESCRIPTION
**Pull request by tadeboro**
Changes in this PR should solve the CI issues with inclusion into the Ansible package.

### CODE REVIEW

**Comment by carchi8py** [comment]
So it looks like it worked. i'm going to make a small change to see if i can get this to work with 2 matrices's so we don't have the code duplicating.

**Comment by tadeboro** [comment]
I duplicated the things in order to avoid downloading docker images multiple times (they are quite large - cca. 1GB). If we add another matrix on collection name, images will need to be downloaded six times

**Comment by carchi8py** [comment]
24 time to be exact. (4 ansible collection * 6 collection). It does end up being faster 9 minutes vs 17. Is there a download/transfer limit we would need to be aware of. If not i would go with the faster version.
https://github.com/ansible-collections/netapp/actions/runs/749190499
you can see the modification i did here for that
https://github.com/ansible-collections/netapp/blob/carchi-test/.github/workflows/main.yml

**Comment by tadeboro** [comment]
I do not think there are any limits, I just wanted to be at least a bit more environment-friendly. I am fine with both solutions. Feel free to replace mine.

**Review by lonico — APPROVED** [review]
Thank you.  I'll give the last word to Chris.

**Comment by carchi8py** [comment]
I think we'll go with the one i made. Mainly so we can tell the collection and the version from the error message with out having to look through the job. 

i've opened the following. https://github.com/ansible-collections/netapp/pull/101

**Pull request closed without merging**
